name:                rl
version:             0.1.0.0
github:              "githubuser/rl"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/rl#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- vector >= 0.12.2
# Pine deps
- sdl2 >= 2.5
- sdl2-image >= 0.1 && < 2.1
- text >= 1.2.3 && < 1.3
- stm >= 2.4 && < 2.6
- mtl >= 2.2
- linear

library:
  source-dirs: src

executables:
  rl-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rl

tests:
  rl-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rl
